### ISSUE TITLE
Uncaught SyntaxError: Unexpected token C

### ISSUE THREAD

**Issue by ryanclark2** [Jacob84/rspec-tree-runner#14] opened 2015-09-29 22:50 UTC
Thanks for creating this!

My first time running this package.  It just threw this error when I tried to run the specs for a controller. 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [rspec-tree-runner](https://github.com/jacobmendoza/rspec-tree-runner) package, v0.2.0
### Stack Trace

Uncaught SyntaxError: Unexpected token C

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fryanclark%2Fsrc%2Fportal%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.19%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fryanclark%2Fsrc%2Fportal%22%5D%7D:1

SyntaxError: Unexpected token C
  at Object.parse (native)
  at RSpecLauncherCommand.module.exports.RSpecLauncherCommand.parseRSpecResult (/Users/ryanclark/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:32:23)
  at /Users/ryanclark/.atom/packages/rspec-tree-runner/lib/rspec-launcher-command.coffee:22:54
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TerminalCommandRunner.module.exports.TerminalCommandRunner.onClose (/Users/ryanclark/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:47:14)
  at ChildProcess.<anonymous> (/Users/ryanclark/.atom/packages/rspec-tree-runner/lib/terminal-command-runner.coffee:1:1)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:764:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
  6x -9:11.6.0 core:close (atom-text-editor.editor.is-focused)
     -9:04.7.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -7:03.4.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -6:55.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:56.4.0 editor:split-selections-into-lines (atom-text-editor.editor.is-focused)
     -0:54.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:51.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:51.3.0 rspec-tree-runner:toggle (atom-text-editor.editor)
     -0:43.3.0 rspec-tree-runner:toggle-spec-file (atom-text-editor.editor.is-focused)
     -0:34.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:20.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:17.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:15.3.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:12 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 rspec-tree-runner:run-tests (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.14
rspec-tree-runner, v0.2.0

# Dev
No dev packages
```

**Comment by jacobmendoza** [comment] 2015-09-30 21:08
Hi @iamryo,

No, really, thanks for your feedback. I'm very sorry that this is the first impression that you're having with the package.

The error is happening when the package is trying to parse the rspec output, which should be in JSON. If you have time and it's possible, I would love to see the output of rspec, to see if there is anything strange that is causing this behaviour. Should be similar to:

Open a terminal
cd project_directoy
rspec --format=json spec/file_that_failed_spec.rb 

That way, I could inspect the output and see if there is something strange with that. In theory, it should allow me to reproduce the issue.

Thanks a lot for your help :)

PS: It would be also useful knowing if it's happening with an specific controller or with all of them.

**Comment by ryanclark2** [comment] 2015-09-30 21:17
Hey @jacobmendoza, 

Thanks for getting back to me!  It's failing on all specs for me.  We're backfilling tests for a project that didn't have very good test coverage - here's one of the files with very few specs:

```
require "rails_helper"

describe Project do
  describe ".active" do
    it "returns projects with an active status" do
      3.times { create(:active_project) }
      2.times { create(:inactive_project) }

      expect(Project.active.count).to eq(3)
    end
  end

  describe ".inactive" do
    it "returns projects where active is false" do
      3.times { create(:active_project) }
      2.times { create(:inactive_project) }

      expect(Project.inactive.count).to eq(2)
    end
  end
end
```

and the JSON formatted rspec output: 

```
➜  portal (master✔) rspec --format=json spec/models/project_spec.rb
{"version":"3.3.2","examples":[{"description":"returns projects with an active
 status","full_description":"Project.active returns projects with an active
 status","status":"passed","file_path":"./spec/models/project_spec.rb","line_number":5,"run_time":0.32820
3,"pending_message":null},{"description":"returns projects where active is 
false","full_description":"Project.inactive returns projects where active is 
false","status":"passed","file_path":"./spec/models/project_spec.rb","line_number":14,"run_time":0.02808
6,"pending_message":null}],"summary":
{"duration":0.357206,"example_count":2,"failure_count":0,"pending_count":0},"summary_line":"2 
examples, 0 failures"}Coverage report generated for RSpec to /Users/ryanclark/src/portal/coverage. 29 / 
49 LOC (59.18%) covered.
```

And of course, now I see the problem! I'm using [SimpleCov](https://github.com/colszowka/simplecov) and it's appending a message after the json response which is causing the parser to barf. 

I can turn that off as an interim solution. I think ideally simplecov should silence itself if rspec is called with json formatting. Not sure how likely that is though.

**Comment by jacobmendoza** [comment] 2015-09-30 21:34
Hey @iamryo. Couldn't be more grateful. 

Can you confirm that it's working without simplecov active?.

As you were saying, I think that simplecov should silence itself when rspec is using the json formatter (or at least return something compatible). I understand that this won't be possible.

First, I will start using simplecov to see if I can understand better the problem. If it makes sense, I'll open an issue. As a hotfix in our side, I was thinking that maybe I can only parse the data between { ... } and avoid the text that appears after.

The package is in an early stage of development, so bugs may appear. If you use it, it would be priceless to have your feedback, not only with bugs but also new features or ideas.

Will keep you posted :).

**Comment by artem-russkikh** [comment] 2016-01-09 15:31
Hi @jacobmendoza! It's working without simplecov, i disable it with ENV variable   

in spec_helper.rb

```
if ENV['SIMPLECOV'] != 'false'
  require 'simplecov'
  SimpleCov.start 'rails'
end
```

![image](https://cloud.githubusercontent.com/assets/3540978/12216798/c22e3036-b70f-11e5-8851-31780985d505.png)

**Comment by jacobmendoza** [comment] 2016-01-12 22:45
Hey @artem-russkikh,

That's very clever. Anyway, I think I should try to find a way to clean the output so it works for simplecov and similar extensions. 

Thanks for posting this, and please, don't hesitate to share all the feedback that you may have :+1:

**Comment by artem-russkikh** [comment] 2016-01-12 23:05
@jacobmendoza take a look at https://github.com/colszowka/simplecov/issues/395

Seems to be that is simplecov problem

**Comment by jacobmendoza** [comment] 2016-02-20 15:07
Hey @iamryo and @artem-russkikh,

I have released a new version that is supposed to fix this issue, cleaning the input and analysing only the Json that comes from RSpec. 

Can you guys give it a go whenever you have time?.

I appreciate!. Thank you!,

PS: Closing the issue, but please, do not hesitate to open again if it fails.

**Closed as completed by jacobmendoza** 2016-02-20 15:07 UTC
Labels: enhancement
